esphome:
  name: Solar1
  friendly_name: Solar1
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
api:
  encryption:
    key: "5D3K/r+a5sVIDN3A4tflgP9QZLvJ4mnkfSqqwBHgI9g="
ota:
  platform: esphome
  password: "b4c8dd7550c637b1ccafcc9017b09fba"
#  num_attempts: 3
#  safe_mode: no
wifi:
  networks:
  - ssid: WiFi-Solar1
  manual_ip:
    static_ip: 10.20.0.96
    gateway: 10.20.0.1
    subnet: 255.255.252.0 
    dns1: 10.20.0.1
  output_power: 20dB
  power_save_mode: none
captive_portal:
uart:
  - rx_pin: GPIO22
    tx_pin: GPIO16
    baud_rate: 9600
    id: uart_1
  - rx_pin: GPIO21
    tx_pin: GPIO17
    baud_rate: 9600
    id: uart_2
modbus:
  - uart_id: uart_1
    id: modbus_1
  - uart_id: uart_2
    id: modbus_2
sensor:
  - platform: wifi_signal
    name: "wifi-power1"
    update_interval: 60s
  - platform: pzemac
    id: pzemac_1
    modbus_id: modbus_1
    current:
      name: "8kw-Current"
      accuracy_decimals: 1
    voltage:
      name: "8kw-Voltage"
      accuracy_decimals: 0
    energy:
      name: "8kw-Energy"
      filters:
        multiply: 0.001
      unit_of_measurement: KWh
      accuracy_decimals: 1
      device_class: "energy"
      state_class: "total_increasing"
    power:
      name: "8kw-Power"
      accuracy_decimals: 0
    frequency:
      name: "8kw-Hz"
    power_factor:
      name: "8kw-PF"
    update_interval: 1s
  - platform: pzemac
    modbus_id: modbus_2
    id: pzemac_2
    current:
      name: "Grid-Current"
      accuracy_decimals: 1
    voltage:
      name: "Grid-Voltage"
      accuracy_decimals: 0
    energy:
      name: "Grid-Energy"
      filters:
        multiply: 0.001
      unit_of_measurement: KWh
      accuracy_decimals: 1
      device_class: "energy"
      state_class: "total_increasing"
    power:
      name: "Grid-Power"
      accuracy_decimals: 0
    update_interval: 1s
  - platform: adc
    name: "Battery-Voltage"
    pin: GPIO35
    id: battery_voltage
    update_interval: 1s
    unit_of_measurement: "V"
    accuracy_decimals: 3
    attenuation: auto
    force_update: true
    filters:
      - median:
            window_size: 60
            send_every: 1
  - platform: adc
    name: "Sun-Level"
    pin: GPIO32
    id: sun
    unit_of_measurement: "V"
    update_interval: 1s
    accuracy_decimals: 2
    attenuation: auto
    force_update: true
    filters:
      - median:
            window_size: 10
            send_every: 1
  - platform: adc
    name: "Temp-Battery"
    pin: GPIO33
    id: temp
    unit_of_measurement: "V"
    update_interval: 1s
    accuracy_decimals: 3
    attenuation: auto
    force_update: true
    filters:
      - median:
            window_size: 10
            send_every: 1
switch:
  - platform: uart
    uart_id: uart_1
    name: "8kw-Reset" 
    data: [0x01, 0x42, 0x80, 0x11]
  - platform: uart
    uart_id: uart_2
    name: "Grid-Reset" 
    data: [0x01, 0x42, 0x80, 0x11]
  - platform: gpio
    name: "power1-relay1"
    pin:
      number: 04
      inverted: false
  - platform: gpio
    name: "power1-relay2"
    pin:
      number: 18
      inverted: false
  - platform: gpio
    name: "power1-relay3"
    pin:
      number: 19
      inverted: false
  - platform: gpio
    name: "power1-relay4"
    pin:
      number: 23
      inverted: false
    
